spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  cloud:
    aws:
      credentials:
        access-key: test
        secret-key: test
      s3:
        region: ap-south-1
        endpoint: https://s3.localhost.localstack.cloud:4566

bucket:
  name: file-bucket